/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Loop Design System tokens
        'primary':        '#0D46F2',
        'background':     '#FFFFFF',
        'text':           '#0A0A0A',
        'surface':        '#F2F2F0',
        'secondary-text': '#8C8C8C',
        // Stitch-generated palette (overrides to ensure compatibility)
        'surface-dim':              '#dadad8',
        'on-secondary-container':   '#eaebff',
        'tertiary-fixed-dim':       '#c7c6c6',
        'error':                    '#ba1a1a',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed-dim':      '#b9c3ff',
        'error-container':          '#ffdad6',
        'surface-container-high':   '#e8e8e6',
        'secondary-fixed':          '#dde1ff',
        'on-secondary-fixed':       '#001257',
        'on-background':            '#1a1c1b',
        'secondary-container':      '#2b57ff',
        'primary-container':        '#5e5c5c',
        'on-surface':               '#1a1c1b',
        'on-surface-variant':       '#424b44',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#ffffff',
        'on-primary-fixed':         '#ffffff',
        'primary-fixed':            '#5e5c5c',
        'primary-fixed-dim':        '#c7c6c6',
        'surface-container-low':    '#f3f3f1',
        'surface-container-lowest': '#ffffff',
        'surface-container':        '#edeeed',
        'surface-variant':          '#dde4dd',
        'surface-bright':           '#f9faf8',
        'outline':                  '#6d7d6e',
        'outline-variant':          '#bdc9bd',
        'inverse-on-surface':       '#eff1ee',
        'inverse-surface':          '#2e312e',
        'inverse-primary':          '#badbbf',
        'scrim':                    '#000000',
        'shadow':                   '#000000',
        'on-error':                 '#ffffff',
        'on-error-container':       '#410002',
        'on-secondary':             '#ffffff',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#001e0c',
        'on-tertiary-fixed':        '#001e0c',
        'on-tertiary-fixed-variant':'#0a3721',
        'secondary':                '#2b57ff',
        'tertiary':                 '#3c6b4d',
        'tertiary-container':       '#beecce',
        'tertiary-fixed':           '#beecce',
      },
      fontFamily: {
        sans: ['"Instrument Sans"', 'system-ui', 'sans-serif'],
        display: ['"Instrument Sans"', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
